export interface IShopStore {
  getPointsBalance(tenantId?: string, childId?: string): Promise<number>;
  updatePoints(action: 'earn' | 'spend', amount: number, detail: string, tenantId?: string, childId?: string): Promise<number>;
  patchPoints(delta: { earn?: number; spend?: number; detail?: string }, tenantId?: string, childId?: string): Promise<number>;
  getShopItems(tenantId?: string): Promise<any[]>;
  saveShopItems(items: any[], tenantId?: string): Promise<void>;
  getShopItemById(id: string, tenantId?: string): Promise<any | null>;
  putShopItem(id: string, data: any, tenantId?: string): Promise<void>;
  deleteShopItem(id: string, tenantId?: string): Promise<void>;
  getRedemptions(tenantId?: string, childId?: string): Promise<any[]>;
  saveRedemptions(items: any[], tenantId?: string, childId?: string): Promise<void>;
  clearFulfilledRedemptions(tenantId?: string, childId?: string): Promise<void>;
  putRedemption(id: string, data: any, tenantId?: string, childId?: string): Promise<void>;
  getRewardBox(tenantId?: string, childId?: string): Promise<any[]>;
  saveRewardBox(items: any[], tenantId?: string, childId?: string): Promise<void>;
  putRewardBoxItem(id: string, data: any, tenantId?: string, childId?: string): Promise<void>;
  deleteRewardBoxItem(id: string, tenantId?: string, childId?: string): Promise<void>;
  getActiveBuffs(tenantId?: string, childId?: string): Promise<any[]>;
  saveActiveBuffs(items: any[], tenantId?: string, childId?: string): Promise<void>;
  putBuff(id: string, data: any, tenantId?: string, childId?: string): Promise<void>;
  deleteBuff(id: string, tenantId?: string, childId?: string): Promise<void>;
  getBountyTasks(tenantId?: string): Promise<any[]>;
  saveBountyTasks(items: any[], tenantId?: string): Promise<void>;
  getBountyTaskById(id: string, tenantId?: string): Promise<any | null>;
  putBountyTask(id: string, data: any, tenantId?: string): Promise<void>;
  deleteBountyTask(id: string, tenantId?: string): Promise<void>;
  getBountySubmissions(dateKey: string, tenantId?: string, childId?: string): Promise<any[]>;
  saveBountySubmissions(dateKey: string, data: any[], tenantId?: string, childId?: string): Promise<void>;
  putBountySubmission(id: string, data: any, tenantId?: string, childId?: string): Promise<void>;
  getBountyCompletions(dateKey: string, tenantId?: string, childId?: string): Promise<any>;
  saveBountyCompletions(dateKey: string, data: any, tenantId?: string, childId?: string): Promise<void>;
  putBountyCompletion(id: string, data: any, tenantId?: string, childId?: string): Promise<void>;
}
